// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: length.proto

package length

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Length int32

const (
	Length_NoLength     Length = 0
	Length_Whole        Length = 1
	Length_Half         Length = 2
	Length_Quarter      Length = 3
	Length_Eighth       Length = 4
	Length_Sixteenth    Length = 5
	Length_Thirtysecond Length = 6
)

// Enum value maps for Length.
var (
	Length_name = map[int32]string{
		0: "NoLength",
		1: "Whole",
		2: "Half",
		3: "Quarter",
		4: "Eighth",
		5: "Sixteenth",
		6: "Thirtysecond",
	}
	Length_value = map[string]int32{
		"NoLength":     0,
		"Whole":        1,
		"Half":         2,
		"Quarter":      3,
		"Eighth":       4,
		"Sixteenth":    5,
		"Thirtysecond": 6,
	}
)

func (x Length) Enum() *Length {
	p := new(Length)
	*p = x
	return p
}

func (x Length) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Length) Descriptor() protoreflect.EnumDescriptor {
	return file_length_proto_enumTypes[0].Descriptor()
}

func (Length) Type() protoreflect.EnumType {
	return &file_length_proto_enumTypes[0]
}

func (x Length) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Length.Descriptor instead.
func (Length) EnumDescriptor() ([]byte, []int) {
	return file_length_proto_rawDescGZIP(), []int{0}
}

var File_length_proto protoreflect.FileDescriptor

var file_length_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x65,
	0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x68, 0x6f, 0x6c, 0x65, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x61, 0x6c, 0x66, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x51,
	0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x69, 0x67, 0x68,
	0x74, 0x68, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x69, 0x78, 0x74, 0x65, 0x65, 0x6e, 0x74,
	0x68, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x68, 0x69, 0x72, 0x74, 0x79, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x10, 0x06, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f, 0x64, 0x69, 0x2f, 0x6c, 0x69, 0x6d, 0x65,
	0x70, 0x69, 0x70, 0x65, 0x73, 0x2d, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2d, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_length_proto_rawDescOnce sync.Once
	file_length_proto_rawDescData = file_length_proto_rawDesc
)

func file_length_proto_rawDescGZIP() []byte {
	file_length_proto_rawDescOnce.Do(func() {
		file_length_proto_rawDescData = protoimpl.X.CompressGZIP(file_length_proto_rawDescData)
	})
	return file_length_proto_rawDescData
}

var file_length_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_length_proto_goTypes = []interface{}{
	(Length)(0), // 0: Length
}
var file_length_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_length_proto_init() }
func file_length_proto_init() {
	if File_length_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_length_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_length_proto_goTypes,
		DependencyIndexes: file_length_proto_depIdxs,
		EnumInfos:         file_length_proto_enumTypes,
	}.Build()
	File_length_proto = out.File
	file_length_proto_rawDesc = nil
	file_length_proto_goTypes = nil
	file_length_proto_depIdxs = nil
}
