// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: symbols/tuplet/tuplet.proto

package tuplet

import (
	boundary "github.com/tomvodi/limepipes-music-model/musicmodel/boundary"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tuplet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoundaryType boundary.Boundary `protobuf:"varint,1,opt,name=boundaryType,proto3,enum=Boundary" json:"boundaryType,omitempty"`
	VisibleNotes uint32            `protobuf:"varint,2,opt,name=visibleNotes,proto3" json:"visibleNotes,omitempty"`
	PlayedNotes  uint32            `protobuf:"varint,3,opt,name=playedNotes,proto3" json:"playedNotes,omitempty"`
}

func (x *Tuplet) Reset() {
	*x = Tuplet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symbols_tuplet_tuplet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tuplet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuplet) ProtoMessage() {}

func (x *Tuplet) ProtoReflect() protoreflect.Message {
	mi := &file_symbols_tuplet_tuplet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuplet.ProtoReflect.Descriptor instead.
func (*Tuplet) Descriptor() ([]byte, []int) {
	return file_symbols_tuplet_tuplet_proto_rawDescGZIP(), []int{0}
}

func (x *Tuplet) GetBoundaryType() boundary.Boundary {
	if x != nil {
		return x.BoundaryType
	}
	return boundary.Boundary(0)
}

func (x *Tuplet) GetVisibleNotes() uint32 {
	if x != nil {
		return x.VisibleNotes
	}
	return 0
}

func (x *Tuplet) GetPlayedNotes() uint32 {
	if x != nil {
		return x.PlayedNotes
	}
	return 0
}

var File_symbols_tuplet_tuplet_proto protoreflect.FileDescriptor

var file_symbols_tuplet_tuplet_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x74,
	0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a,
	0x06, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x0c, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e,
	0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x52, 0x0c, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x76, 0x69,
	0x73, 0x69, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x44, 0x5a, 0x42,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f,
	0x64, 0x69, 0x2f, 0x6c, 0x69, 0x6d, 0x65, 0x70, 0x69, 0x70, 0x65, 0x73, 0x2d, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x2f, 0x74, 0x75, 0x70, 0x6c,
	0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_symbols_tuplet_tuplet_proto_rawDescOnce sync.Once
	file_symbols_tuplet_tuplet_proto_rawDescData = file_symbols_tuplet_tuplet_proto_rawDesc
)

func file_symbols_tuplet_tuplet_proto_rawDescGZIP() []byte {
	file_symbols_tuplet_tuplet_proto_rawDescOnce.Do(func() {
		file_symbols_tuplet_tuplet_proto_rawDescData = protoimpl.X.CompressGZIP(file_symbols_tuplet_tuplet_proto_rawDescData)
	})
	return file_symbols_tuplet_tuplet_proto_rawDescData
}

var file_symbols_tuplet_tuplet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_symbols_tuplet_tuplet_proto_goTypes = []interface{}{
	(*Tuplet)(nil),         // 0: Tuplet
	(boundary.Boundary)(0), // 1: Boundary
}
var file_symbols_tuplet_tuplet_proto_depIdxs = []int32{
	1, // 0: Tuplet.boundaryType:type_name -> Boundary
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_symbols_tuplet_tuplet_proto_init() }
func file_symbols_tuplet_tuplet_proto_init() {
	if File_symbols_tuplet_tuplet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_symbols_tuplet_tuplet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tuplet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_symbols_tuplet_tuplet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_symbols_tuplet_tuplet_proto_goTypes,
		DependencyIndexes: file_symbols_tuplet_tuplet_proto_depIdxs,
		MessageInfos:      file_symbols_tuplet_tuplet_proto_msgTypes,
	}.Build()
	File_symbols_tuplet_tuplet_proto = out.File
	file_symbols_tuplet_tuplet_proto_rawDesc = nil
	file_symbols_tuplet_tuplet_proto_goTypes = nil
	file_symbols_tuplet_tuplet_proto_depIdxs = nil
}
