// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: barline.proto

package barline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Regular    Type = 0
	Type_Heavy      Type = 1
	Type_HeavyHeavy Type = 2
	Type_LightHeavy Type = 3
	Type_HeavyLight Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Regular",
		1: "Heavy",
		2: "HeavyHeavy",
		3: "LightHeavy",
		4: "HeavyLight",
	}
	Type_value = map[string]int32{
		"Regular":    0,
		"Heavy":      1,
		"HeavyHeavy": 2,
		"LightHeavy": 3,
		"HeavyLight": 4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_barline_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_barline_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_barline_proto_rawDescGZIP(), []int{0}
}

type Time int32

const (
	Time_NoTimee      Time = 0
	Time_Segno        Time = 1
	Time_Dalsegno     Time = 2
	Time_Fine         Time = 3
	Time_DacapoAlFine Time = 4
	Time_Repeat       Time = 5 // a normal |: ... :| repeat lines
)

// Enum value maps for Time.
var (
	Time_name = map[int32]string{
		0: "NoTimee",
		1: "Segno",
		2: "Dalsegno",
		3: "Fine",
		4: "DacapoAlFine",
		5: "Repeat",
	}
	Time_value = map[string]int32{
		"NoTimee":      0,
		"Segno":        1,
		"Dalsegno":     2,
		"Fine":         3,
		"DacapoAlFine": 4,
		"Repeat":       5,
	}
)

func (x Time) Enum() *Time {
	p := new(Time)
	*p = x
	return p
}

func (x Time) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Time) Descriptor() protoreflect.EnumDescriptor {
	return file_barline_proto_enumTypes[1].Descriptor()
}

func (Time) Type() protoreflect.EnumType {
	return &file_barline_proto_enumTypes[1]
}

func (x Time) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Time.Descriptor instead.
func (Time) EnumDescriptor() ([]byte, []int) {
	return file_barline_proto_rawDescGZIP(), []int{1}
}

type Barline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	Time Time `protobuf:"varint,2,opt,name=time,proto3,enum=Time" json:"time,omitempty"`
}

func (x *Barline) Reset() {
	*x = Barline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Barline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barline) ProtoMessage() {}

func (x *Barline) ProtoReflect() protoreflect.Message {
	mi := &file_barline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barline.ProtoReflect.Descriptor instead.
func (*Barline) Descriptor() ([]byte, []int) {
	return file_barline_proto_rawDescGZIP(), []int{0}
}

func (x *Barline) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Regular
}

func (x *Barline) GetTime() Time {
	if x != nil {
		return x.Time
	}
	return Time_NoTimee
}

var File_barline_proto protoreflect.FileDescriptor

var file_barline_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3f, 0x0a, 0x07, 0x42, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x2a, 0x4e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x75,
	0x6c, 0x61, 0x72, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x65, 0x61, 0x76, 0x79, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x76, 0x79, 0x48, 0x65, 0x61, 0x76, 0x79, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x48, 0x65, 0x61, 0x76, 0x79, 0x10, 0x03,
	0x12, 0x0e, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x76, 0x79, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x10, 0x04,
	0x2a, 0x54, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x54, 0x69,
	0x6d, 0x65, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x65, 0x67, 0x6e, 0x6f, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x44, 0x61, 0x6c, 0x73, 0x65, 0x67, 0x6e, 0x6f, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x69, 0x6e, 0x65, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x61, 0x63, 0x61,
	0x70, 0x6f, 0x41, 0x6c, 0x46, 0x69, 0x6e, 0x65, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x10, 0x05, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f, 0x64, 0x69, 0x2f, 0x6c, 0x69, 0x6d,
	0x65, 0x70, 0x69, 0x70, 0x65, 0x73, 0x2d, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2d, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x62, 0x61,
	0x72, 0x6c, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_barline_proto_rawDescOnce sync.Once
	file_barline_proto_rawDescData = file_barline_proto_rawDesc
)

func file_barline_proto_rawDescGZIP() []byte {
	file_barline_proto_rawDescOnce.Do(func() {
		file_barline_proto_rawDescData = protoimpl.X.CompressGZIP(file_barline_proto_rawDescData)
	})
	return file_barline_proto_rawDescData
}

var file_barline_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_barline_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_barline_proto_goTypes = []interface{}{
	(Type)(0),       // 0: Type
	(Time)(0),       // 1: Time
	(*Barline)(nil), // 2: Barline
}
var file_barline_proto_depIdxs = []int32{
	0, // 0: Barline.type:type_name -> Type
	1, // 1: Barline.time:type_name -> Time
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_barline_proto_init() }
func file_barline_proto_init() {
	if File_barline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_barline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Barline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barline_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_barline_proto_goTypes,
		DependencyIndexes: file_barline_proto_depIdxs,
		EnumInfos:         file_barline_proto_enumTypes,
		MessageInfos:      file_barline_proto_msgTypes,
	}.Build()
	File_barline_proto = out.File
	file_barline_proto_rawDesc = nil
	file_barline_proto_goTypes = nil
	file_barline_proto_depIdxs = nil
}
