// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: symbols/note.proto

package symbols

import (
	length "github.com/tomvodi/limepipes-music-model/musicmodel/length"
	pitch "github.com/tomvodi/limepipes-music-model/musicmodel/pitch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Note struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pitch  pitch.Pitch   `protobuf:"varint,1,opt,name=pitch,proto3,enum=Pitch" json:"pitch,omitempty"`
	Length length.Length `protobuf:"varint,2,opt,name=length,proto3,enum=Length" json:"length,omitempty"`
	Dots   uint32        `protobuf:"varint,3,opt,name=dots,proto3" json:"dots,omitempty"`
}

func (x *Note) Reset() {
	*x = Note{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symbols_note_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_symbols_note_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_symbols_note_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetPitch() pitch.Pitch {
	if x != nil {
		return x.Pitch
	}
	return pitch.Pitch(0)
}

func (x *Note) GetLength() length.Length {
	if x != nil {
		return x.Length
	}
	return length.Length(0)
}

func (x *Note) GetDots() uint32 {
	if x != nil {
		return x.Dots
	}
	return 0
}

var File_symbols_note_proto protoreflect.FileDescriptor

var file_symbols_note_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x70, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0c, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x59, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x50, 0x69, 0x74, 0x63, 0x68, 0x52, 0x05,
	0x70, 0x69, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x6f, 0x74, 0x73, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f, 0x64, 0x69,
	0x2f, 0x6c, 0x69, 0x6d, 0x65, 0x70, 0x69, 0x70, 0x65, 0x73, 0x2d, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_symbols_note_proto_rawDescOnce sync.Once
	file_symbols_note_proto_rawDescData = file_symbols_note_proto_rawDesc
)

func file_symbols_note_proto_rawDescGZIP() []byte {
	file_symbols_note_proto_rawDescOnce.Do(func() {
		file_symbols_note_proto_rawDescData = protoimpl.X.CompressGZIP(file_symbols_note_proto_rawDescData)
	})
	return file_symbols_note_proto_rawDescData
}

var file_symbols_note_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_symbols_note_proto_goTypes = []interface{}{
	(*Note)(nil),       // 0: Note
	(pitch.Pitch)(0),   // 1: Pitch
	(length.Length)(0), // 2: Length
}
var file_symbols_note_proto_depIdxs = []int32{
	1, // 0: Note.pitch:type_name -> Pitch
	2, // 1: Note.length:type_name -> Length
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_symbols_note_proto_init() }
func file_symbols_note_proto_init() {
	if File_symbols_note_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_symbols_note_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Note); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_symbols_note_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_symbols_note_proto_goTypes,
		DependencyIndexes: file_symbols_note_proto_depIdxs,
		MessageInfos:      file_symbols_note_proto_msgTypes,
	}.Build()
	File_symbols_note_proto = out.File
	file_symbols_note_proto_rawDesc = nil
	file_symbols_note_proto_goTypes = nil
	file_symbols_note_proto_depIdxs = nil
}
