// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: symbol.proto

package musicmodel

import (
	symbols "github.com/tomvodi/limepipes-music-model/musicmodel/symbols"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Symbol represents a musical symbol.
// It can be a Note or a Rest.
// Symbol doesn't use the oneof pattern because it is not makes the resulting structs
// in Go too nested.
type Symbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Note *symbols.Note `protobuf:"bytes,1,opt,name=note,proto3,oneof" json:"note,omitempty"`
	Rest *symbols.Rest `protobuf:"bytes,2,opt,name=rest,proto3,oneof" json:"rest,omitempty"`
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symbol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_symbol_proto_rawDescGZIP(), []int{0}
}

func (x *Symbol) GetNote() *symbols.Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *Symbol) GetRest() *symbols.Rest {
	if x != nil {
		return x.Rest
	}
	return nil
}

var File_symbol_proto protoreflect.FileDescriptor

var file_symbol_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x1e, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x1e, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x48, 0x01, 0x52, 0x04, 0x72, 0x65, 0x73, 0x74, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x65,
	0x73, 0x74, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f, 0x64, 0x69, 0x2f, 0x6c, 0x69, 0x6d, 0x65, 0x70, 0x69, 0x70,
	0x65, 0x73, 0x2d, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_symbol_proto_rawDescOnce sync.Once
	file_symbol_proto_rawDescData = file_symbol_proto_rawDesc
)

func file_symbol_proto_rawDescGZIP() []byte {
	file_symbol_proto_rawDescOnce.Do(func() {
		file_symbol_proto_rawDescData = protoimpl.X.CompressGZIP(file_symbol_proto_rawDescData)
	})
	return file_symbol_proto_rawDescData
}

var file_symbol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_symbol_proto_goTypes = []interface{}{
	(*Symbol)(nil),       // 0: Symbol
	(*symbols.Note)(nil), // 1: Note
	(*symbols.Rest)(nil), // 2: Rest
}
var file_symbol_proto_depIdxs = []int32{
	1, // 0: Symbol.note:type_name -> Note
	2, // 1: Symbol.rest:type_name -> Rest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_symbol_proto_init() }
func file_symbol_proto_init() {
	if File_symbol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_symbol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Symbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_symbol_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_symbol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_symbol_proto_goTypes,
		DependencyIndexes: file_symbol_proto_depIdxs,
		MessageInfos:      file_symbol_proto_msgTypes,
	}.Build()
	File_symbol_proto = out.File
	file_symbol_proto_rawDesc = nil
	file_symbol_proto_goTypes = nil
	file_symbol_proto_depIdxs = nil
}
