// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: plugin/v1/messages/export.proto

package messages

import (
	tune "github.com/tomvodi/limepipes-plugin-api/musicmodel/v1/tune"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tunes to export.
	// In multi tune file formats like bww, this will contain all the tunes in the file.
	// For single tune file formats like MusicXML, this must contain a single tune
	// if multiple tunes are provided, an error will be returned.
	ExportTunes []*tune.Tune `protobuf:"bytes,1,rep,name=export_tunes,json=exportTunes,proto3" json:"export_tunes,omitempty"`
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_export_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_export_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetExportTunes() []*tune.Tune {
	if x != nil {
		return x.ExportTunes
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// In case it should be exported to data, this will contain the raw data.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_export_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_export_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExportToFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tunes to export.
	// In multi tune file formats like bww, this will contain all the tunes in the file.
	// For single tune file formats like MusicXML, this must contain a single tune
	// if multiple tunes are provided, an error will be returned.
	ExportTunes []*tune.Tune `protobuf:"bytes,1,rep,name=export_tunes,json=exportTunes,proto3" json:"export_tunes,omitempty"`
	// The path to the file to export the tunes to.
	// The path must not be empty.
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *ExportToFileRequest) Reset() {
	*x = ExportToFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_export_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportToFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportToFileRequest) ProtoMessage() {}

func (x *ExportToFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_export_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportToFileRequest.ProtoReflect.Descriptor instead.
func (*ExportToFileRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_export_proto_rawDescGZIP(), []int{2}
}

func (x *ExportToFileRequest) GetExportTunes() []*tune.Tune {
	if x != nil {
		return x.ExportTunes
	}
	return nil
}

func (x *ExportToFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ExportToFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportToFileResponse) Reset() {
	*x = ExportToFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_export_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportToFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportToFileResponse) ProtoMessage() {}

func (x *ExportToFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_export_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportToFileResponse.ProtoReflect.Descriptor instead.
func (*ExportToFileResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_export_proto_rawDescGZIP(), []int{3}
}

var File_plugin_v1_messages_export_proto protoreflect.FileDescriptor

var file_plugin_v1_messages_export_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1d, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x75, 0x6e, 0x65, 0x2f, 0x74, 0x75, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x74, 0x75, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x75,
	0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x75, 0x6e, 0x65,
	0x2e, 0x54, 0x75, 0x6e, 0x65, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x75, 0x6e,
	0x65, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x13, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x75, 0x6e, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x75, 0x6e, 0x65, 0x52,
	0x0b, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x54, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0xcb, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x0b, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f, 0x64, 0x69, 0x2f,
	0x6c, 0x69, 0x6d, 0x65, 0x70, 0x69, 0x70, 0x65, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x50, 0x56, 0x4d, 0xaa, 0x02, 0x12,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x56, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0xca, 0x02, 0x12, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0xe2, 0x02, 0x1e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5c, 0x56, 0x31, 0x5c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x3a, 0x3a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_v1_messages_export_proto_rawDescOnce sync.Once
	file_plugin_v1_messages_export_proto_rawDescData = file_plugin_v1_messages_export_proto_rawDesc
)

func file_plugin_v1_messages_export_proto_rawDescGZIP() []byte {
	file_plugin_v1_messages_export_proto_rawDescOnce.Do(func() {
		file_plugin_v1_messages_export_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_v1_messages_export_proto_rawDescData)
	})
	return file_plugin_v1_messages_export_proto_rawDescData
}

var file_plugin_v1_messages_export_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugin_v1_messages_export_proto_goTypes = []any{
	(*ExportRequest)(nil),        // 0: plugin.v1.messages.ExportRequest
	(*ExportResponse)(nil),       // 1: plugin.v1.messages.ExportResponse
	(*ExportToFileRequest)(nil),  // 2: plugin.v1.messages.ExportToFileRequest
	(*ExportToFileResponse)(nil), // 3: plugin.v1.messages.ExportToFileResponse
	(*tune.Tune)(nil),            // 4: musicmodel.v1.tune.Tune
}
var file_plugin_v1_messages_export_proto_depIdxs = []int32{
	4, // 0: plugin.v1.messages.ExportRequest.export_tunes:type_name -> musicmodel.v1.tune.Tune
	4, // 1: plugin.v1.messages.ExportToFileRequest.export_tunes:type_name -> musicmodel.v1.tune.Tune
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_messages_export_proto_init() }
func file_plugin_v1_messages_export_proto_init() {
	if File_plugin_v1_messages_export_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_v1_messages_export_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_export_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ExportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_export_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ExportToFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_export_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExportToFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_v1_messages_export_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_messages_export_proto_goTypes,
		DependencyIndexes: file_plugin_v1_messages_export_proto_depIdxs,
		MessageInfos:      file_plugin_v1_messages_export_proto_msgTypes,
	}.Build()
	File_plugin_v1_messages_export_proto = out.File
	file_plugin_v1_messages_export_proto_rawDesc = nil
	file_plugin_v1_messages_export_proto_goTypes = nil
	file_plugin_v1_messages_export_proto_depIdxs = nil
}
