// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: plugin/v1/messages/parse.proto

package messages

import (
	tune "github.com/tomvodi/limepipes-plugin-api/musicmodel/v1/tune"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParsedTune struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tune that was imported.
	Tune *tune.Tune `protobuf:"bytes,1,opt,name=tune,proto3" json:"tune,omitempty"`
	// The data with which the tune can be restored to a file.
	// In multi tune file formats like bww, this data will represent a single tune.
	// For single tune file formats like MusicXML, this data will always be empty.
	TuneFileData []byte `protobuf:"bytes,2,opt,name=tune_file_data,json=tuneFileData,proto3" json:"tune_file_data,omitempty"`
}

func (x *ParsedTune) Reset() {
	*x = ParsedTune{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_parse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedTune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTune) ProtoMessage() {}

func (x *ParsedTune) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_parse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTune.ProtoReflect.Descriptor instead.
func (*ParsedTune) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_parse_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedTune) GetTune() *tune.Tune {
	if x != nil {
		return x.Tune
	}
	return nil
}

func (x *ParsedTune) GetTuneFileData() []byte {
	if x != nil {
		return x.TuneFileData
	}
	return nil
}

type ParseFromFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Path to local file
}

func (x *ParseFromFileRequest) Reset() {
	*x = ParseFromFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_parse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseFromFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFromFileRequest) ProtoMessage() {}

func (x *ParseFromFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_parse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFromFileRequest.ProtoReflect.Descriptor instead.
func (*ParseFromFileRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_parse_proto_rawDescGZIP(), []int{1}
}

func (x *ParseFromFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ParseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Data to parse into tunes
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_parse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_parse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_parse_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ParseFromFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tunes that could be parsed.
	// In multi tune file formats like bww, this will contain all the tunes in the file.
	// For single tune file formats like MusicXML, this will contain a single tune.
	Tunes []*ParsedTune `protobuf:"bytes,1,rep,name=tunes,proto3" json:"tunes,omitempty"`
}

func (x *ParseFromFileResponse) Reset() {
	*x = ParseFromFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_parse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseFromFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFromFileResponse) ProtoMessage() {}

func (x *ParseFromFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_parse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFromFileResponse.ProtoReflect.Descriptor instead.
func (*ParseFromFileResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_parse_proto_rawDescGZIP(), []int{3}
}

func (x *ParseFromFileResponse) GetTunes() []*ParsedTune {
	if x != nil {
		return x.Tunes
	}
	return nil
}

type ParseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tunes that could be parsed.
	// In multi tune file formats like bww, this will contain all the tunes in the file.
	// For single tune file formats like MusicXML, this will contain a single tune.
	Tunes []*ParsedTune `protobuf:"bytes,1,rep,name=tunes,proto3" json:"tunes,omitempty"`
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_messages_parse_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_messages_parse_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_messages_parse_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResponse) GetTunes() []*ParsedTune {
	if x != nil {
		return x.Tunes
	}
	return nil
}

var File_plugin_v1_messages_parse_proto protoreflect.FileDescriptor

var file_plugin_v1_messages_parse_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x1a, 0x1d, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x75, 0x6e, 0x65, 0x2f, 0x74, 0x75, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x54, 0x75, 0x6e,
	0x65, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x75, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x74, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x75, 0x6e, 0x65, 0x52, 0x04, 0x74, 0x75, 0x6e, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x74, 0x75, 0x6e, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x75, 0x6e, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x14, 0x50, 0x61, 0x72, 0x73, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x22, 0x0a, 0x0c, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4d,
	0x0a, 0x15, 0x50, 0x61, 0x72, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x74, 0x75, 0x6e, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x64, 0x54, 0x75, 0x6e, 0x65, 0x52, 0x05, 0x74, 0x75, 0x6e, 0x65, 0x73, 0x22, 0x45, 0x0a,
	0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x05, 0x74, 0x75, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x54, 0x75, 0x6e, 0x65, 0x52, 0x05, 0x74,
	0x75, 0x6e, 0x65, 0x73, 0x42, 0xca, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42,
	0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d, 0x76, 0x6f, 0x64,
	0x69, 0x2f, 0x6c, 0x69, 0x6d, 0x65, 0x70, 0x69, 0x70, 0x65, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x50, 0x56, 0x4d, 0xaa,
	0x02, 0x12, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x56, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0xca, 0x02, 0x12, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5c, 0x56, 0x31,
	0x5c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0xe2, 0x02, 0x1e, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x3a, 0x3a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_v1_messages_parse_proto_rawDescOnce sync.Once
	file_plugin_v1_messages_parse_proto_rawDescData = file_plugin_v1_messages_parse_proto_rawDesc
)

func file_plugin_v1_messages_parse_proto_rawDescGZIP() []byte {
	file_plugin_v1_messages_parse_proto_rawDescOnce.Do(func() {
		file_plugin_v1_messages_parse_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_v1_messages_parse_proto_rawDescData)
	})
	return file_plugin_v1_messages_parse_proto_rawDescData
}

var file_plugin_v1_messages_parse_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_v1_messages_parse_proto_goTypes = []any{
	(*ParsedTune)(nil),            // 0: plugin.v1.messages.ParsedTune
	(*ParseFromFileRequest)(nil),  // 1: plugin.v1.messages.ParseFromFileRequest
	(*ParseRequest)(nil),          // 2: plugin.v1.messages.ParseRequest
	(*ParseFromFileResponse)(nil), // 3: plugin.v1.messages.ParseFromFileResponse
	(*ParseResponse)(nil),         // 4: plugin.v1.messages.ParseResponse
	(*tune.Tune)(nil),             // 5: musicmodel.v1.tune.Tune
}
var file_plugin_v1_messages_parse_proto_depIdxs = []int32{
	5, // 0: plugin.v1.messages.ParsedTune.tune:type_name -> musicmodel.v1.tune.Tune
	0, // 1: plugin.v1.messages.ParseFromFileResponse.tunes:type_name -> plugin.v1.messages.ParsedTune
	0, // 2: plugin.v1.messages.ParseResponse.tunes:type_name -> plugin.v1.messages.ParsedTune
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_v1_messages_parse_proto_init() }
func file_plugin_v1_messages_parse_proto_init() {
	if File_plugin_v1_messages_parse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_v1_messages_parse_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ParsedTune); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_parse_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ParseFromFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_parse_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ParseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_parse_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ParseFromFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_messages_parse_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ParseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_v1_messages_parse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_messages_parse_proto_goTypes,
		DependencyIndexes: file_plugin_v1_messages_parse_proto_depIdxs,
		MessageInfos:      file_plugin_v1_messages_parse_proto_msgTypes,
	}.Build()
	File_plugin_v1_messages_parse_proto = out.File
	file_plugin_v1_messages_parse_proto_rawDesc = nil
	file_plugin_v1_messages_parse_proto_goTypes = nil
	file_plugin_v1_messages_parse_proto_depIdxs = nil
}
